version: '3.9'
services:
  s1:
    build: services/service1
    container_name: service1
    image: thegreatgamma/avl-task:s1
    networks: 
      - my-network
    ports:
      - 8080:8080
  s2:
      build: services/service2
      container_name: service2
      image: thegreatgamma/avl-task:s2
      networks: 
        - my-network
      ports:
       - 8081:8080

networks:
  my-network:
    driver: bridge