version: '3.9'
services:
  s1:
    build: service1
    container_name: service1
    networks: 
        - my-network
    ports:
      - 8080:8080

  s2:
      build: service2
      container_name: service2
      networks: 
        - my-network
      ports:
       - 8081:8080

networks:
  my-network:
    driver: bridge